var GAME_LEVELS = [
  ["                                                                               x",
   "                                                                               x",
   "                                                                               x",
   "x                                                                              x",
   "x                                                                           o  x",
   "x                                                                       xxxxxxxx",
   "x                                                                   xxx        x",
   "x                                                                xxx           x",
   "x                                                                         ~xxxxx",
   "x                                             xxxxx         xxxxx              x",
   "x        o                         o o                                        ~x",
   "x       xxx                      xxxxxx             x!!!!!!x                   x",
   "x @   xxxxx         o  o  o                         x!!!!!!x                   x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "                                                                                "],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxvxxxxvxxxvxvxxxxxxxxxxxxxxxxxxvxxxxvxvxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                         x                                                      x",
   "x                                                         x                                                      x",
   "x        @              x                                ~x                                                      x",
   "xxx xxxxxxxxxxxxxxxxxxxxx o                               x                                                      x",
   "x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx                           x                                                      x",
   "xxxxxxxxxvxxxxvxxxxxxxxxx             o          x        x                                                      x",
   "x                                    xxx         x!!!!!!!!x                                                      x",
   "x                                                x!!!!!!!!x                                                      x",
   "x                                                x!!!!!!!!x                                                      x",
   "x o                     xxxxxxxxxxxx xxxxxxxxxxxxxxvxxvxvxx                                                      x",
   "xxxxxxxxx                                                                                                        x",
   "x                                                                                                                x",
   "x                o                                                                                               x",
   "x            xxxxxxxx                                                                                           ~x",
   "x o                                                            xxxxxxxx                                          x",
   "xxxxxxxx                                                                                                        ~x",
   "x                                     xxxxxxxxx            xxxx               xxxxxxxxxx                         x",
   "x           o                                                                                                   ~x",
   "x       xxxxxxxx                                     xxxxxx                                  xxxxx               x",
   "x                      xxxxxxxxxx                                                                                x",
   "x                                                                                                           o    x",
   "x                                                                                                     xxxxxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxvxxxxxxxxxxxxxvxxxxxxxxxxxvxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxx",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                                             x",
   "x                                                                                 o                           x",
   "x                                                                             xxxxxx                          x",
   "x                                                                                                           ~ x",
   "x                                                           o       xxxxx                       o             x",
   "x                            o                            xxxxxx                              xxxxx           x",
   "x                          xxxxxx                                                                           ~ x",
   "x                                                 xxxxx                                                       x",
   "x              xxxxx                  xxxxxxxx                                                                x",
   "x                                                                                ~x                           x",
   "x        xxx                                                                      x                           x",
   "x  @ xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       o   x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
